### ISSUE TITLE
WRK/HTMB - How-to's?

### ISSUE THREAD

**Issue by Icydeath** [Lygre/addons#3]
Hi, I'm trying to get the WKR addon to work. If all possible, could you put in the readme on how to use the addon? I would like to utilize it and the HTMB addon. Thanks in advance.

**Comment by Lygre** [comment]
I do apologize. WKR, Ambus, and HTMB have been removed from the 'live' branch at this time. 
Though functional, I would like to finish a more thorough debugging before publishing a ReadMe for them--out of concern for public safety and selfishly hoping to avoid a wave of "You got me banned" complaints.
HTMB may eventually be removed completely, as it is proving to be an alarmingly powerful tool.
All this being said, they are still available for the time being on the 'dev' branch and should you be so inclined to go through the code and find the addon commands, feel free to use them _**AT YOUR OWN RISK**_.
